---

nxapi_state: enabled
bash_shell_state: enabled
scp_server_state: enabled
tacacs_state: enabled
ospf_state: enabled
bgp_state: enabled
interface_vlan_state: enabled
vn_segment_state: enabled
lacp_state: enabled
lldp_state: enabled
bfd_state: enabled
nv_state: enabled
evpn_state: enabled

ospf_process: 1
ospf_area: 0.0.0.0
ospf_router_id: 3.3.3.3

asn: 65001
router_id: 3.3.3.3
afi_1: ipv4-ucast
afi_2: l2vpn-evpn
bgp_neighbor_1: 1.1.1.1
bgp_neighbor_2: 2.2.2.2
source_interface: lo0

nve: nve1